import os

qtunit = int(ARGUMENTS.get('qtunit', 0))

env = Environment()
env.ParseConfig('cppunit-config --cflags --libs')
env.Append(CCFLAGS = ["-g"])
if qtunit==1 :
	env.ParseConfig('pkg-config qt-mt --cflags --libs')
	env.Append(LIBS = ['qttestrunner'])
	env.Append(CCFLAGS = ["-DGUI_ENABLED"])

env.Append(BUILDERS = {'Test' : Builder(action = "./$SOURCE && touch $TARGET")})

env.Import('sources')
env.Import('includePaths')

env.Append(CCFLAGS=includePaths)

objects = env.Object(sources)

env.Program('#BioscenaTests', objects)
env.Test('BioscenaTests.passed', '#BioscenaTests' )



