# Canvia les seguents definicions com convingui
CC=gcc
CPPC=gxx
RM=del
EXEC=out.exe
BUILDER=buildnum
CPPSOURCES:= $(wildcard *.cpp)
CSOURCES:=$(wildcard *.c)
OBJSCPP:=$(CPPSOURCES:.cpp=.o)
OBJSC:=$(CSOURCES:.c=.o)
CFLAGS= -g
LDLIBS=-lm 

default: copirrait ${EXEC}

copirrait:
	@echo KKEPerians UNLTD generic makefile file 

dep: copirrait 
	@echo --- Generant dependencies
	$(CPPC) -M $(CPPSOURCES) $(CSOURCES) > .depend

clean: copirrait 
	@echo --- Eliminant arxius intermedis
	$(RM) *.o 
	$(RM) ${EXEC}

include .depend

${EXEC}: $(OBJSCPP) $(OBJSC)
	@echo --- Linkant $@
	${CPPC} $(OBJSCPP) $(OBJSC) ${LDLIBS} -o ${EXEC} 
	buildnum

$(OBJSC) %.o: %.c
	@echo --- Compilant $<
	${CC} ${CFLAGS} -c $< -o $@


$(OBJSCPP) : %.o: %.cpp
	@echo --- Compilant $<
	${CPPC} ${CFLAGS} -c $< -o $@


