name: CI

on:
  push: # on push commits at any branch
  pull_request: # on external PR
  workflow_dispatch: # on demand

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y scons libcppunit-dev lcov
          pip install scons-tool-loader scons-tool-gcccov
      - name: Unit tests
        run: |
          scons
          lcov --capture lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
